package modeloClinicaFrame;

public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        miFuncionario = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        miMascote = new javax.swing.JMenuItem();
        miServico = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenu();
        miAgendamento = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        miAgenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("REGISTRAR");

        miFuncionario.setText("VETERINARIO");
        miFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(miFuncionario);

        miCliente.setText("CLIENTE");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(miCliente);

        miMascote.setText("MASCOTE");
        miMascote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMascoteActionPerformed(evt);
            }
        });
        menuCadastro.add(miMascote);

        miServico.setText("SERVICO");
        miServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miServicoActionPerformed(evt);
            }
        });
        menuCadastro.add(miServico);

        jMenuBar1.add(menuCadastro);

        menuAgendamento.setText("ATENDIMENTOS");

        miAgendamento.setText("CRIAR");
        miAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgendamentoActionPerformed(evt);
            }
        });
        menuAgendamento.add(miAgendamento);

        jMenuBar1.add(menuAgendamento);

        menuAgenda.setText("CONFERIR");

        miAgenda.setText("AGENDAMENTO");
        miAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgendaActionPerformed(evt);
            }
        });
        menuAgenda.add(miAgenda);

        jMenuBar1.add(menuAgenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFuncionarioActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_miFuncionarioActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        TelaCliente telaCliente = new TelaCliente();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_miClienteActionPerformed

    private void miServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miServicoActionPerformed
        TelaServico telaServico = new TelaServico();
        telaServico.setVisible(true);
    }//GEN-LAST:event_miServicoActionPerformed

    private void miAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgendamentoActionPerformed
        TelaAgendamento telaAgendamento = new TelaAgendamento();
        telaAgendamento.setVisible(true);
    }//GEN-LAST:event_miAgendamentoActionPerformed

    private void miAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgendaActionPerformed
        TelaAgenda telaAgenda = new TelaAgenda();
        telaAgenda.setVisible(true);
    }//GEN-LAST:event_miAgendaActionPerformed

    private void miMascoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMascoteActionPerformed
        TelaFuncionario telaFuncionario = new TelaFuncionario();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_miMascoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem miAgenda;
    private javax.swing.JMenuItem miAgendamento;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miFuncionario;
    private javax.swing.JMenuItem miMascote;
    private javax.swing.JMenuItem miServico;
    // End of variables declaration//GEN-END:variables
}
